import React, { useState, useEffect } from 'react';
import {
  FileText,
  Printer,
  Copy,
  Check,
  RefreshCw,
  Sparkles,
  TrendingUp,
  Award,
  AlertTriangle,
  Lightbulb,
  ShieldCheck,
  Download,
  BarChart3,
} from 'lucide-react';
import { api } from '../services/api';
import { ManagementReport, NavigationTab } from '../types';

interface ReportsPageProps {
  datasetId: string;
  onNavigate?: (tab: NavigationTab) => void;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ datasetId, onNavigate }) => {
  const [report, setReport] = useState<ManagementReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [copied, setCopied] = useState(false);

  const loadReport = async (fresh = false, overrideId?: string) => {
    const idToFetch = overrideId || datasetId;
    if (fresh) setRefreshing(true);
    else setLoading(true);

    try {
      const rep = await api.getReport(idToFetch, fresh);
      setReport(rep);
    } catch (err) {
      console.error(err);
      if (idToFetch !== 'sales-default-01') {
        try {
          const fallback = await api.getReport('sales-default-01', fresh);
          setReport(fallback);
        } catch {
          // ignore
        }
      }
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    if (datasetId) loadReport();
  }, [datasetId]);

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    if (!report) return;
    const md = `# ${report.title}
**Dataset**: ${report.datasetName} | **Date**: ${report.generatedAt}

## Executive Summary
${report.executiveSummary}

## Key Performance Indicators
${report.keyKpisSummary}

## Major Trends
${report.majorTrends.map((t) => `- **${t.period}**: ${t.observation} (Fact: ${t.fact})`).join('\n')}

## Top Performers
${report.topPerformers.map((p) => `- **${p.segment}**: ${p.metrics} - ${p.takeaway}`).join('\n')}

## Areas Requiring Attention
${report.areasRequiringAttention.map((a) => `- [${a.severity.toUpperCase()}] **${a.title}**: ${a.details} (Action: ${a.suggestedAction})`).join('\n')}

## Recommended Areas to Investigate
${report.recommendedInvestigativeAreas.map((r, i) => `${i + 1}. ${r}`).join('\n')}

*Generated by Analyze Data platform using verified computational facts.*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-4 py-16 flex flex-col items-center justify-center space-y-4 text-center">
        <div className="w-10 h-10 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin" />
        <p className="text-sm font-medium text-slate-300">Synthesizing executive management report...</p>
        <p className="text-xs text-slate-500">Compiling verified KPIs, trend evidence, and actionable briefings</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-16 text-center space-y-6">
        <h3 className="text-xl font-bold text-slate-100">Management Report Unavailable</h3>
        <p className="text-xs text-slate-400">Could not generate a report for the current dataset.</p>
        <div className="flex items-center justify-center gap-3">
          {onNavigate && (
            <button
              onClick={() => onNavigate('dashboard')}
              className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold"
            >
              <BarChart3 className="w-4 h-4 text-indigo-400" />
              <span>Open KPI Dashboard</span>
            </button>
          )}
          <button
            onClick={() => loadReport(true, 'sales-default-01')}
            className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold"
          >
            Generate Sample Report
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-6 print:p-0 print:m-0 print:max-w-none">
      {/* Top Toolbar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-slate-900 border border-slate-800 print:hidden">
        <div className="flex items-center space-x-2 text-xs text-slate-400">
          <FileText className="w-4 h-4 text-indigo-400" />
          <span>Management Report for:</span>
          <span className="font-semibold text-slate-200">{report.datasetName}</span>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => loadReport(true)}
            disabled={refreshing}
            className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold flex items-center space-x-1.5 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
            <span>Regenerate</span>
          </button>
          <button
            onClick={handleCopyMarkdown}
            className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold flex items-center space-x-1.5 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied MD' : 'Copy Markdown'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center space-x-1.5 transition-colors shadow-lg shadow-indigo-600/20"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* Printable Report Document Card */}
      <article className="p-8 sm:p-12 rounded-3xl bg-slate-900 border border-slate-800 space-y-8 shadow-2xl print:bg-white print:text-black print:border-none print:shadow-none print:p-0">
        {/* Memo Header */}
        <div className="border-b border-slate-800 pb-6 print:border-slate-300">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold uppercase tracking-widest text-indigo-400 print:text-indigo-700">
              Analyze Data · Executive Briefing
            </span>
            <span className="text-xs text-slate-400 font-mono print:text-slate-600">
              {report.generatedAt}
            </span>
          </div>
          <h1 className="mt-3 text-3xl sm:text-4xl font-black text-slate-100 print:text-black tracking-tight">
            {report.title}
          </h1>
          <p className="mt-1 text-xs text-slate-400 print:text-slate-600">
            Source Dataset: <span className="font-semibold text-slate-300 print:text-slate-800">{report.datasetName}</span> · Verified Computation
          </p>
        </div>

        {/* Section 1: Executive Summary */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700 flex items-center space-x-2">
            <Sparkles className="w-4 h-4 text-indigo-400 print:text-indigo-600" />
            <span>1. Executive Summary</span>
          </h2>
          <div className="p-4 rounded-2xl bg-slate-950/60 border border-slate-800 text-sm leading-relaxed text-slate-200 print:bg-slate-50 print:text-slate-800 print:border-slate-200">
            {report.executiveSummary}
          </div>
        </section>

        {/* Section 2: Key KPIs */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700">
            2. Core Performance Indicators
          </h2>
          <p className="text-xs text-slate-300 print:text-slate-800 leading-relaxed font-medium">
            {report.keyKpisSummary}
          </p>
        </section>

        {/* Section 3: Major Trends */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700 flex items-center space-x-2">
            <TrendingUp className="w-4 h-4 text-cyan-400 print:text-cyan-600" />
            <span>3. Major Trends & Trajectory</span>
          </h2>
          <div className="space-y-2.5">
            {report.majorTrends.map((trend, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-slate-950/40 border border-slate-800 text-xs space-y-1 print:bg-slate-50 print:border-slate-200"
              >
                <div className="font-bold text-slate-200 print:text-black flex items-center justify-between">
                  <span>{trend.period}</span>
                  <span className="text-[10px] text-emerald-400 print:text-emerald-700 font-mono">Verified Fact</span>
                </div>
                <p className="text-slate-300 print:text-slate-700">{trend.observation}</p>
                <p className="text-[11px] text-slate-500 print:text-slate-600 font-mono pt-1">
                  Evidence: {trend.fact}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 4: Top Performers */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700 flex items-center space-x-2">
            <Award className="w-4 h-4 text-amber-400 print:text-amber-600" />
            <span>4. Top Commercial Performers</span>
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {report.topPerformers.map((perf, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-slate-950/40 border border-slate-800 text-xs space-y-1 print:bg-slate-50 print:border-slate-200"
              >
                <div className="font-bold text-slate-200 print:text-black">{perf.segment}</div>
                <div className="text-[11px] text-indigo-400 print:text-indigo-700 font-mono font-semibold">
                  {perf.metrics}
                </div>
                <p className="text-slate-400 print:text-slate-600 text-[11px] pt-1">{perf.takeaway}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 5: Areas Requiring Attention */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700 flex items-center space-x-2">
            <AlertTriangle className="w-4 h-4 text-rose-400 print:text-rose-600" />
            <span>5. Areas Requiring Executive Attention</span>
          </h2>
          <div className="space-y-2.5">
            {report.areasRequiringAttention.map((area, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-rose-500/5 border border-rose-500/20 text-xs space-y-1 print:bg-rose-50 print:border-rose-200"
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-rose-300 print:text-rose-800">{area.title}</span>
                  <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-rose-500/20 text-rose-300">
                    {area.severity}
                  </span>
                </div>
                <p className="text-slate-300 print:text-slate-700">{area.details}</p>
                <div className="text-[11px] text-amber-300 print:text-amber-800 pt-1 font-medium">
                  Recommendation: {area.suggestedAction}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Section 6: Recommended Investigative Areas */}
        <section className="space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400 print:text-slate-700 flex items-center space-x-2">
            <Lightbulb className="w-4 h-4 text-amber-400 print:text-amber-600" />
            <span>6. Recommended Areas to Investigate</span>
          </h2>
          <div className="p-4 rounded-2xl bg-slate-950/60 border border-slate-800 space-y-2 print:bg-slate-50 print:border-slate-200">
            <p className="text-xs text-slate-400 print:text-slate-600">
              Note: These represent targeted investigative hypotheses, separated from established factual metrics.
            </p>
            <ul className="space-y-1.5 text-xs text-slate-200 print:text-slate-800 list-disc list-inside">
              {report.recommendedInvestigativeAreas.map((rec, idx) => (
                <li key={idx} className="leading-relaxed">
                  {rec}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* Report Footer */}
        <div className="pt-6 border-t border-[#111439]/20 dark:border-slate-700/80 print:border-slate-300 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center space-x-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block"></span>
            <span className="font-bold text-[#111439] dark:text-[#f8f8f9]">Analyze Data · Verified Math Grounding</span>
            <span className="text-[#374182] dark:text-[#a8b0d8]">| Deterministic Executive Audit</span>
          </div>
          <div className="flex items-center space-x-2">
            <span className="px-3 py-1 rounded-full bg-[#111439]/5 dark:bg-slate-800 border border-[#111439]/15 dark:border-slate-700 text-[#111439] dark:text-[#f8f8f9] font-bold text-xs">
              Quality Index: {report.dataQualitySummary.score}/100
            </span>
          </div>
        </div>
      </article>
    </div>
  );
};
